const STORAGE_PREFIX='duckSimulatorV18_slot_';
let currentSlot=1,game=null,devUnlocked=false,miniInterval=null;
const $=id=>document.getElementById(id);
const defaultGame=()=>({name:'Coincoin',money:500,hunger:80,clean:80,sleep:80,happy:80,wet:0,room:'city',duckColor:'#ffd84d',duckX:450,duckY:320,birth:Date.now(),lastVisit:Date.now(),sleepUntil:0,sleepDuration:60*60*1000,school:0,job:'Aucun',jobXP:0,weather:'Soleil',hour:8,inventory:{salad:0,bread:0,fish:0,meal:0,soap:0,towel:0,prep:0},objects:{},placed:[],dead:false});
const rooms={city:{wall:'#9bd3ae',floor:'#6c8f5f',back:'city',objects:[]},living:{wall:'#f4d58d',floor:'#a47148',back:'home',objects:[['doorKitchen','🚪',25,430,'emoji'],['sofa','sofa',90,455,'css'],['tv','tv',820,345,'css']]},kitchen:{wall:'#d8f3dc',floor:'#b7b7a4',back:'home',objects:[['doorLiving','🚪',25,430,'emoji'],['fridge','fridge',95,310,'css'],['counter','counter',400,470,'css'],['pan','pan',720,470,'css'],['plateSpot','plate',940,485,'css']]},bath:{wall:'#ade8f4',floor:'#48cae4',back:'home',objects:[['doorLiving','🚪',25,430,'emoji'],['bathTub','bath',90,470,'css'],['water','🚿',340,240,'item'],['soapObj','🧼',580,455,'item'],['towelObj','🧺',850,455,'item']]},bedroom:{wall:'#cdb4db',floor:'#9d4edd',back:'home',objects:[['doorLiving','🚪',25,430,'emoji'],['bed','bed',95,440,'css'],['lightSwitch','💡',760,260,'emoji']]},shop:{wall:'#f8edeb',floor:'#d5bdaf',back:'home',objects:[['foodShelf','shelf',90,350,'css'],['cashier','cash',850,455,'css']]},school:{wall:'#caf0f8',floor:'#90e0ef',back:'home',objects:[['board','schoolBoard',360,180,'css'],['desk','counter',440,470,'css'],['teacher','🧑‍🏫',850,390,'emoji']]}};
document.addEventListener('DOMContentLoaded',bind);
function bind(){
 $('play').onclick=showSaveSelect;$('backStart').onclick=()=>{hideAll();show('start')};$('create').onclick=createGame;$('bagBtn').onclick=()=>$('inventoryPanel').classList.toggle('hidden');$('reset').onclick=resetGame;
 $('quickFridge').onclick=quickFridge;$('quickFeed').onclick=quickFeed;$('jobMiniBtn').onclick=()=>mini('job');$('studyBtn').onclick=studyQuiz;$('save').onclick=()=>{save();msg('Sauvegardé 💾')};$('closeMini').onclick=closeMini;
 $('devOpenStart').onclick=openDev;$('devOpenGame').onclick=openDev;$('devOpenSleep').onclick=openDev;$('devClose').onclick=()=>hide('devOverlay');$('devUnlock').onclick=unlockDev;$('devApply').onclick=applyDev;$('devWake').onclick=()=>{game.sleepUntil=0;msg('Dodo terminé');update()};
 document.querySelectorAll('button[data-room]').forEach(b=>b.onclick=()=>{if(!isSleeping())goRoom(b.dataset.room)});
 document.querySelectorAll('#joystick button').forEach(b=>b.onclick=()=>moveDuck(b.dataset.move));
 $('duck').ondragstart=e=>{if(isSleeping())return e.preventDefault();e.dataTransfer.setData('type','duck');e.dataTransfer.setData('id','duck')};$('duck').ondragover=e=>e.preventDefault();$('duck').ondrop=e=>{e.preventDefault();const id=e.dataTransfer.getData('id'),type=e.dataTransfer.getData('type');if(type==='inventory'||type==='placed'||type==='item')useOnDuck(id)};
 $('room').ondragover=e=>e.preventDefault();$('room').ondrop=roomDrop;
}
function show(id){$(id).classList.remove('hidden')}function hide(id){$(id).classList.add('hidden')}function hideAll(){['start','saveSelect','setup','game'].forEach(hide)}
function showSaveSelect(){hideAll();show('saveSelect');renderSlots()}function renderSlots(){const box=$('saveSlots');box.innerHTML='';for(let i=1;i<=3;i++){let name='Vide';const raw=localStorage.getItem(STORAGE_PREFIX+i);if(raw){try{name=JSON.parse(raw).name||'Sauvegarde'}catch(e){}}const d=document.createElement('div');d.className='saveSlot';d.innerHTML=`<h3>Slot ${i} : ${name}</h3><button onclick="loadSlot(${i})">Jouer</button><button onclick="newSlot(${i})">Nouvelle partie</button><button onclick="deleteSlot(${i})" class="danger">Supprimer</button>`;box.appendChild(d)}}
function loadSlot(i){currentSlot=i;const raw=localStorage.getItem(STORAGE_PREFIX+i);if(raw){game=JSON.parse(raw);normalize();hideAll();show('game');startLoops();update()}else newSlot(i)}function newSlot(i){currentSlot=i;game=defaultGame();hideAll();show('setup')}function deleteSlot(i){if(confirm('Supprimer ?')){localStorage.removeItem(STORAGE_PREFIX+i);renderSlots()}}
function createGame(){game.name=$('duckName').value||'Coincoin';game.duckColor=$('duckColor').value;game.birth=Date.now();hideAll();show('game');startLoops();update()}function normalize(){game={...defaultGame(),...game};game.inventory={...defaultGame().inventory,...(game.inventory||{})};game.objects=game.objects||{};game.placed=game.placed||{}}
function save(){if(game)localStorage.setItem(STORAGE_PREFIX+currentSlot,JSON.stringify(game))}function startLoops(){if(!window.started){setInterval(passTime,60000);setInterval(updateSleep,1000);setInterval(gravity,80);window.started=true}}
function getAge(){return Math.floor((Date.now()-game.birth)/86400000)}function getYears(){return getAge()}
function update(){if(!game)return;checkDeath100();$('title').textContent=game.name;$('money').textContent=game.money;$('hunger').value=game.hunger;$('clean').value=game.clean;$('sleep').value=game.sleep;$('happy').value=game.happy;$('wet').value=game.wet;$('clock').textContent=(game.hour<10?'0':'')+game.hour+'h';$('weather').textContent=game.weather;document.documentElement.style.setProperty('--duck',game.duckColor);document.documentElement.style.setProperty('--wall',rooms[game.room].wall);document.documentElement.style.setProperty('--floor',rooms[game.room].floor);$('duck').style.left=game.duckX+'px';$('duck').style.top=game.duckY+'px';drawBackdrop();updateAge();drawObjects();drawPlaced();drawInventory();updateWet();updateCover();updateSleep();save()}
function checkDeath100(){if(getYears()>=100&&!game.dead){game.dead=true;show('deathScene');msg('Mort naturelle à 100 ans 🪦')}if(game.dead)show('deathScene')}function updateAge(){let y=getYears(),st='Bébé canard',sc=.75;if(y>=2){st='Enfant';sc=.9}if(y>=5){st='Ado';sc=1.05}if(y>=9){st='Adulte';sc=1.2}if(y>=70){st='Ancien';sc=1.25}$('age').textContent=y+' ans';$('stage').textContent=st;$('job').textContent=game.job+' XP '+game.jobXP;$('duck').style.transform=`scale(${sc})`}
function drawBackdrop(){const b=$('backdrop');b.innerHTML='';if(game.room==='city'){b.innerHTML=`<div class="cityMap"><div class="cityTile" onclick="goRoom('living')">🏠 Maison</div><div class="cityTile" onclick="goRoom('shop')">🏪 Magasin</div><div class="cityTile" onclick="goRoom('school')">🏫 École</div><div class="cityTile" onclick="mini('job')">💼 Job</div><div class="cityTile" onclick="mini('food')">🥬 Nourriture</div><div class="cityTile" onclick="randomWeather()">🌦️ Météo</div><div class="cityTile" onclick="watchTV()">📺 BFMDuck</div><div class="cityTile" onclick="quickFridge()">🧊 Frigo rapide</div></div>`;return}b.innerHTML='<div class="wallGrid"></div><div class="door" style="left:20px;top:520px" onclick="goRoom(`city`)">Ville</div><div class="windowBig" style="left:70%;top:70px"></div>'}
function drawObjects(){$('objects').innerHTML='';if(!game.objects[game.room])game.objects[game.room]={};rooms[game.room].objects.forEach(([id,visual,x,y,type])=>{if(!game.objects[game.room][id])game.objects[game.room][id]={x,y};const p=game.objects[game.room][id],d=document.createElement('div');d.className='object';d.draggable=true;d.style.left=p.x+'px';d.style.top=p.y+'px';if(type==='css')d.classList.add('furn',visual);else{d.classList.add('emoji');d.textContent=visual;d.onclick=()=>objectClick(id)}d.ondragstart=e=>{e.dataTransfer.setData('type',type==='item'?'item':'object');e.dataTransfer.setData('id',id)};$('objects').appendChild(d)})}
function objectClick(id){if(id==='tv')watchTV();if(id==='fridge')quickFridge();if(id==='counter')prepareFood();if(id==='pan')cookFood();if(id==='foodShelf')msg('Rayon nourriture : utilise les boutons magasin rapide.');if(id==='cashier')msg('Caisse validée 🧾');if(['water','soapObj','towelObj'].includes(id))useOnDuck(id);if(id==='lightSwitch')msg('Lumière changée 💡');if(id==='board'||id==='desk')studyQuiz()}
function drawPlaced(){$('placed').innerHTML='';game.placed.filter(p=>p.room===game.room).forEach(p=>{const d=document.createElement('div');d.className='placedItem';d.textContent=icon(p.item);d.draggable=true;d.style.left=p.x+'px';d.style.top=p.y+'px';d.ondragstart=e=>{e.dataTransfer.setData('type','placed');e.dataTransfer.setData('id',p.id)};$('placed').appendChild(d)})}
function drawInventory(){const keys=['salad','bread','fish','prep','meal','soap','towel'];$('inventory').innerHTML='';keys.forEach(id=>{const d=document.createElement('div');d.className='slot';d.draggable=(game.inventory[id]||0)>0;d.textContent=(game.inventory[id]||0)>0?icon(id)+' '+game.inventory[id]:'—';d.ondragstart=e=>{if((game.inventory[id]||0)<=0)return;e.dataTransfer.setData('type','inventory');e.dataTransfer.setData('id',id)};$('inventory').appendChild(d)})}
function icon(id){return{salad:'🥬',bread:'🍞',fish:'🐟',meal:'🍲',soap:'🧼',towel:'🧺',prep:'🔪'}[id]||'❓'}
function goRoom(r){game.room=r;game.duckX=450;game.duckY=320;update()}function moveDuck(dir){if(isSleeping())return;const d=$('duck');let step=38;if(dir==='run'){d.classList.add('running');step=90;dir='right';setTimeout(()=>d.classList.remove('running'),600)}else{d.classList.add('walking');setTimeout(()=>d.classList.remove('walking'),450)}if(dir==='up')game.duckY-=step;if(dir==='down')game.duckY+=step;if(dir==='left')game.duckX-=step;if(dir==='right')game.duckX+=step;game.duckX=clamp(game.duckX,0,$('room').clientWidth-150);game.duckY=clamp(game.duckY,0,$('room').clientHeight-155);checkDuckPlace();update()}
function roomDrop(e){e.preventDefault();if(isSleeping())return;const type=e.dataTransfer.getData('type'),id=e.dataTransfer.getData('id'),r=$('room').getBoundingClientRect(),x=clamp(e.clientX-r.left-55,0,r.width-140),y=clamp(e.clientY-r.top-55,0,r.height-140);if(type==='duck'){game.duckX=x;game.duckY=y;checkDuckPlace()}else if(type==='inventory'){placeInventory(id,x,y)}else if(type==='placed'){movePlaced(id,x,y)}else{if(!game.objects[game.room])game.objects[game.room]={};game.objects[game.room][id]={x,y}}update()}
function gravity(){if(!game||isSleeping()||game.dead)return;const ground=$('room').clientHeight-170;let ch=false;if(game.duckY<ground&&game.room!=='city'){game.duckY=Math.min(ground,game.duckY+6);ch=true}game.placed.forEach(p=>{if(p.room===game.room&&p.y<ground+40){p.y=Math.min(ground+40,p.y+5);ch=true}});if(ch)update()}
function placeInventory(id,x,y){if(!game.inventory[id])return;game.inventory[id]--;game.placed.push({id:'p'+Date.now()+Math.random(),item:id,room:game.room,x,y});msg(icon(id)+' posé.')}function movePlaced(pid,x,y){const p=game.placed.find(i=>i.id===pid);if(p){p.x=x;p.y=y}}function consumePlaced(pid){const i=game.placed.findIndex(p=>p.id===pid);if(i>=0)game.placed.splice(i,1)}
function useOnDuck(id){let item=id;if(id.startsWith('p')){const p=game.placed.find(x=>x.id===id);if(!p)return;item=p.item;consumePlaced(id)}if(item==='meal'){game.hunger=clamp(game.hunger+45,0,100);$('duck').classList.add('eating');setTimeout(()=>$('duck').classList.remove('eating'),1600);msg('Le canard mange.')}else if(item==='water'){game.wet=100;$('duck').classList.add('showering');setTimeout(()=>$('duck').classList.remove('showering'),2000);msg('Douche : mouillé.')}else if(item==='soap'||item==='soapObj'){game.clean=clamp(game.clean+35,0,100);msg('Savon : propreté +35.')}else if(item==='towel'||item==='towelObj'){game.wet=0;msg('Séché.')}else msg('Il faut cuisiner avant.');update()}
function quickFridge(){game.inventory.salad++;game.inventory.bread++;msg('Frigo rapide : + salade + pain.');update()}function quickFeed(){if(game.inventory.meal<=0)return msg('Pas de repas. Cuisine avant.');game.inventory.meal--;useOnDuck('meal')}function prepareFood(){if(game.room!=='kitchen')return msg('Va en cuisine.');const food=game.placed.find(p=>p.room==='kitchen'&&['salad','bread','fish'].includes(p.item));if(food){consumePlaced(food.id);game.inventory.prep++;msg('Préparation terminée 🔪');update()}else msg('Pose nourriture dans la cuisine.')}function cookFood(){if(game.room!=='kitchen')return msg('Va en cuisine.');if(game.inventory.prep<=0)return msg('Prépare avant.');game.inventory.prep--;game.inventory.meal++;msg('Repas cuit 🍳');update()}
function checkDuckPlace(){if(game.room==='bedroom'){const b=game.objects.bedroom?.bed;if(b&&distance(game.duckX,game.duckY,b.x,b.y)<210)sleepDuck()}}function sleepDuck(){game.sleep=100;game.sleepUntil=Date.now()+game.sleepDuration;$('duck').classList.add('sleepAnim');msg('Le canard dort.');updateSleep()}
function updateCover(){const c=$('cover');if(isSleeping()&&game.room==='bedroom'){c.classList.remove('hidden');c.style.left=game.duckX+5+'px';c.style.top=game.duckY+80+'px'}else{c.classList.add('hidden');$('duck').classList.remove('sleepAnim')}}function updateWet(){const d=$('drops');if(game.wet>0){d.classList.remove('hidden');d.style.left=game.duckX+85+'px';d.style.top=game.duckY+5+'px'}else d.classList.add('hidden')}
function buyItem(id){const p={salad:20,bread:15,fish:35,soap:25,towel:40};if(game.money<p[id])return msg('Pas assez.');game.money-=p[id];game.inventory[id]++;update()}function mini(t){show('miniOverlay');$('miniArea').innerHTML='';clearInterval(miniInterval);if(t==='food')miniFood();else tapMini(t,8,()=>miniReward(t))}function closeMini(){hide('miniOverlay');$('miniArea').innerHTML='';clearInterval(miniInterval)}
function miniFood(){$('miniTitle').textContent='Nourriture';let score=0;const a=$('miniArea'),b=document.createElement('div');b.className='basket';b.style.left='180px';a.appendChild(b);a.onmousemove=e=>{const r=a.getBoundingClientRect();b.style.left=clamp(e.clientX-r.left-45,0,r.width-95)+'px'};function spawn(){const f=document.createElement('div');f.className='fallingFood';f.textContent='🥬';f.style.left=Math.random()*(a.clientWidth-40)+'px';f.style.top='-40px';a.appendChild(f);let y=-40;const fall=setInterval(()=>{y+=6;f.style.top=y+'px';const fx=parseInt(f.style.left),bx=parseInt(b.style.left);if(y>a.clientHeight-80&&fx>bx-30&&fx<bx+95){clearInterval(fall);f.remove();score++;if(score>=5){game.inventory.salad+=2;update();closeMini()}}if(y>a.clientHeight){clearInterval(fall);f.remove()}},30)}miniInterval=setInterval(spawn,650)}
function tapMini(title,needed,reward){$('miniTitle').textContent=title;$('miniInfo').textContent='Clique les étoiles';let score=0;const a=$('miniArea');function spawn(){const t=document.createElement('div');t.className='tapTarget';t.textContent='⭐';t.style.left=Math.random()*(a.clientWidth-80)+'px';t.style.top=Math.random()*(a.clientHeight-80)+'px';t.onclick=()=>{score++;t.remove();$('miniInfo').textContent='Score : '+score+'/'+needed;if(score>=needed){reward();update();closeMini()}else spawn()};a.appendChild(t)}spawn()}function miniReward(t){if(t==='clean')game.clean=100;if(t==='job'){game.money+=120;game.job='Employé';game.jobXP++}if(t==='school')studyQuiz(true);msg('Mini-jeu réussi : '+t)}function studyQuiz(fromMini=false){const ans=fromMini?'4':prompt('École : 2 + 2 = ?');if(ans==='4'){game.school++;game.jobXP++;$('duck').classList.add('schoolAnim');setTimeout(()=>$('duck').classList.remove('schoolAnim'),2500);msg('Bonne réponse : 2+2=4. XP +1')}else msg('Raté. Ici 2+2 = 4, pas 22 millions 😭');update()}
function watchTV(){game.happy=clamp(game.happy+6,0,100);msg('BFMDuck : le canard regarde les infos.');update()}function randomWeather(){const w=['Soleil','Pluie 🌧️','Orage ⛈️','Neige ❄️'];game.weather=w[Math.floor(Math.random()*w.length)];if(game.weather.includes('Pluie'))game.wet=80;update()}
function openDev(){show('devOverlay');$('devLocked').classList.toggle('hidden',devUnlocked);$('devPanel').classList.toggle('hidden',!devUnlocked);fillDev()}function unlockDev(){if($('devCode').value==='2004'){devUnlocked=true;$('devLocked').classList.add('hidden');$('devPanel').classList.remove('hidden');fillDev()}else alert('Code faux')}function fillDev(){if(!game)game=defaultGame();$('devMoney').value=game.money;$('devAge').value=getYears();$('devHunger').value=game.hunger;$('devClean').value=game.clean;$('devSleep').value=game.sleep;$('devHappy').value=game.happy;$('devWet').value=game.wet}function applyDev(){game.money=+devMoney.value;game.birth=Date.now()-+devAge.value*86400000;game.hunger=clamp(+devHunger.value,0,100);game.clean=clamp(+devClean.value,0,100);game.sleep=clamp(+devSleep.value,0,100);game.happy=clamp(+devHappy.value,0,100);game.wet=clamp(+devWet.value,0,100);game.dead=false;hide('deathScene');update()}
function passTime(){if(!game||isSleeping()||game.dead)return;game.hour=(game.hour+1)%24;game.hunger=clamp(game.hunger-2,0,100);game.clean=clamp(game.clean-1,0,100);game.sleep=clamp(game.sleep-2,0,100);game.happy=clamp(game.happy-1,0,100);game.wet=clamp(game.wet-4,0,100);game.lastVisit=Date.now();update()}function updateSleep(){if(!game)return;if(isSleeping()){show('sleepOverlay');const l=game.sleepUntil-Date.now();$('timer').textContent=Math.floor(l/60000)+' min '+Math.floor((l%60000)/1000)+' sec'}else hide('sleepOverlay');updateCover()}function isSleeping(){return game&&Date.now()<game.sleepUntil}
function resetGame(){if(confirm('Recommencer ?')){localStorage.removeItem(STORAGE_PREFIX+currentSlot);location.reload()}}function msg(t){$('msg').textContent=t}function clamp(v,min,max){return Math.min(max,Math.max(min,v))}function distance(x1,y1,x2,y2){return Math.sqrt((x1-x2)**2+(y1-y2)**2)}
