const STORAGE_PREFIX='duckSimulatorV20_slot_';
let currentSlot=1,game=null,devUnlocked=false,miniInterval=null,musicOsc=null,musicCtx=null;
const $=id=>document.getElementById(id);
const defaultSettings=()=>({volume:.06,music:false,dark:false,timeSpeed:1,autosave:true,oneDayOneYear:true});
const defaultGame=()=>({name:'Coincoin',money:500,hunger:80,clean:80,sleep:80,happy:80,wet:0,love:0,room:'city',duckColor:'#ffd84d',duckX:450,duckY:320,birth:Date.now(),lastVisit:Date.now(),sleepUntil:0,sleepDuration:60*60*1000,school:0,job:'Aucun',jobXP:0,weather:'Soleil',hour:8,inventory:{salad:0,bread:0,fish:0,meal:0,soap:0,towel:0,prep:0,toy:0},objects:{},placed:[],dead:false,car:false,fuel:100,partner:null,married:false,children:[],pet:null,petHappy:80,followers:0,achievements:[],journal:[],settings:defaultSettings(),
daily:{lastDay:0,giftClaimed:false,mission:'',promo:'',event:'',progress:0,done:false},
collection:[],
dailyStats:{meals:0,school:0,earned:0,garden:0,bath:0,tv:0}
});
const rooms={city:{wall:'#9bd3ae',floor:'#6c8f5f',back:'city',objects:[]},living:{wall:'#f4d58d',floor:'#a47148',back:'home',objects:[['doorKitchen','🚪',25,430,'emoji'],['sofa','sofa',90,455,'css'],['tv','tv',820,345,'css']]},kitchen:{wall:'#d8f3dc',floor:'#b7b7a4',back:'home',objects:[['doorLiving','🚪',25,430,'emoji'],['fridge','fridge',95,310,'css'],['counter','counter',400,470,'css'],['pan','pan',720,470,'css'],['plateSpot','plate',940,485,'css']]},bath:{wall:'#ade8f4',floor:'#48cae4',back:'home',objects:[['doorLiving','🚪',25,430,'emoji'],['bathTub','bath',90,470,'css'],['water','🚿',340,240,'item'],['soapObj','🧼',580,455,'item'],['towelObj','🧺',850,455,'item']]},bedroom:{wall:'#cdb4db',floor:'#9d4edd',back:'home',objects:[['doorLiving','🚪',25,430,'emoji'],['bed','bed',95,440,'css'],['lightSwitch','💡',760,260,'emoji']]},garden:{wall:'#95d5b2',floor:'#52b788',back:'garden',objects:[['doorLiving','🚪',25,430,'emoji'],['pool','pool',460,470,'css'],['ball','⚽',850,455,'emoji']]},shop:{wall:'#f8edeb',floor:'#d5bdaf',back:'home',objects:[['foodShelf','shelf',90,350,'css'],['cashier','cash',850,455,'css']]},school:{wall:'#caf0f8',floor:'#90e0ef',back:'home',objects:[['board','schoolBoard',360,180,'css'],['desk','counter',440,470,'css'],['teacher','🧑‍🏫',850,390,'emoji']]}};
const profiles=[{name:'Canardine',need:35},{name:'Quackina',need:60},{name:'Daisy',need:75}];
document.addEventListener('DOMContentLoaded',bind);
function bind(){
 $('play').onclick=showSaveSelect;$('backStart').onclick=()=>{hideAll();show('start')};$('create').onclick=createGame;$('bagBtn').onclick=()=>$('inventoryPanel').classList.toggle('hidden');$('settingsBtn').onclick=openSettings;$('reset').onclick=resetGame;
 $('quickFridge').onclick=quickFridge;$('quickFeed').onclick=quickFeed;$('save').onclick=()=>{save();msg('Sauvegardé 💾')};$('closeMini').onclick=closeMini;$('closeModal').onclick=()=>hide('modalOverlay');$('driveClose').onclick=()=>{hide('driveOverlay');document.onkeydown=null};
 $('devOpenStart').onclick=openDev;$('devOpenGame').onclick=openDev;$('devOpenSleep').onclick=openDev;$('devClose').onclick=()=>hide('devOverlay');$('devUnlock').onclick=unlockDev;$('devApply').onclick=applyDev;$('devWake').onclick=()=>{game.sleepUntil=0;msg('Dodo terminé');update()};
 document.querySelectorAll('button[data-room]').forEach(b=>b.onclick=()=>{if(!isSleeping())goRoom(b.dataset.room)});
 document.querySelectorAll('#joystick button').forEach(b=>b.onclick=()=>moveDuck(b.dataset.move));
 $('duck').ondragstart=e=>{if(isSleeping())return e.preventDefault();e.dataTransfer.setData('type','duck');e.dataTransfer.setData('id','duck')};$('duck').ondragover=e=>e.preventDefault();$('duck').ondrop=e=>{e.preventDefault();const id=e.dataTransfer.getData('id'),type=e.dataTransfer.getData('type');if(type==='inventory'||type==='placed'||type==='item')useOnDuck(id)};
 $('room').ondragover=e=>e.preventDefault();$('room').ondrop=roomDrop;
}
function show(id){$(id).classList.remove('hidden')}function hide(id){$(id).classList.add('hidden')}function hideAll(){['start','saveSelect','setup','game'].forEach(hide)}
function showSaveSelect(){hideAll();show('saveSelect');renderSlots()}function renderSlots(){const box=$('saveSlots');box.innerHTML='';for(let i=1;i<=3;i++){let name='Vide';const raw=localStorage.getItem(STORAGE_PREFIX+i);if(raw){try{name=JSON.parse(raw).name||'Sauvegarde'}catch(e){}}const d=document.createElement('div');d.className='saveSlot';d.innerHTML=`<h3>Slot ${i} : ${name}</h3><button onclick="loadSlot(${i})">Jouer</button><button onclick="newSlot(${i})">Nouvelle partie</button><button onclick="deleteSlot(${i})" class="danger">Supprimer</button>`;box.appendChild(d)}}
function loadSlot(i){currentSlot=i;const raw=localStorage.getItem(STORAGE_PREFIX+i);if(raw){game=JSON.parse(raw);normalize();hideAll();show('game');startLoops();applySettings();checkDaily();update()}else newSlot(i)}function newSlot(i){currentSlot=i;game=defaultGame();hideAll();show('setup')}function deleteSlot(i){if(confirm('Supprimer ?')){localStorage.removeItem(STORAGE_PREFIX+i);renderSlots()}}
function createGame(){game.name=$('duckName').value||'Coincoin';game.duckColor=$('duckColor').value;game.birth=Date.now();addJournal('Début de l’aventure. Le propriétaire a l’air bizarre.');hideAll();show('game');startLoops();applySettings();checkDaily();update()}
function normalize(){game={...defaultGame(),...game};game.inventory={...defaultGame().inventory,...(game.inventory||{})};game.objects=game.objects||{};game.placed=Array.isArray(game.placed)?game.placed:[];game.achievements=game.achievements||[];game.journal=game.journal||[];game.settings={...defaultSettings(),...(game.settings||{})};game.daily={lastDay:0,giftClaimed:false,mission:'',promo:'',event:'',progress:0,done:false,...(game.daily||{})};game.collection=game.collection||[];game.dailyStats={meals:0,school:0,earned:0,garden:0,bath:0,tv:0,...(game.dailyStats||{})};game.children=game.children||[]}
function save(){if(game&&game.settings.autosave)localStorage.setItem(STORAGE_PREFIX+currentSlot,JSON.stringify(game));else if(game)localStorage.setItem(STORAGE_PREFIX+currentSlot,JSON.stringify(game))}
function startLoops(){if(!window.started){setInterval(passTime,60000);setInterval(updateSleep,1000);setInterval(gravity,80);window.started=true}}
function getAge(){return Math.floor((Date.now()-game.birth)/86400000)}function getYears(){return game.settings.oneDayOneYear?getAge():Math.floor(getAge()/30)}
function update(){if(!game)return;checkDeath100();$('title').textContent=game.name;$('money').textContent=game.money;$('hunger').value=game.hunger;$('clean').value=game.clean;$('sleep').value=game.sleep;$('happy').value=game.happy;$('wet').value=game.wet;$('love').value=game.love;$('clock').textContent=(game.hour<10?'0':'')+game.hour+'h';$('weather').textContent=game.weather;document.documentElement.style.setProperty('--duck',game.duckColor);document.documentElement.style.setProperty('--wall',rooms[game.room].wall);document.documentElement.style.setProperty('--floor',rooms[game.room].floor);$('duck').style.left=game.duckX+'px';$('duck').style.top=game.duckY+'px';drawBackdrop();drawDailyPanel();drawRoomActions();updateAge();drawObjects();drawPlaced();drawFamily();drawInventory();updateWet();updateCover();updateSleep();if(game.settings.autosave)save()}
function checkDeath100(){if(getYears()>=100&&!game.dead){game.dead=true;show('deathScene');unlock('Canard centenaire');addJournal('J’ai atteint 100 ans. Sacré voyage.');msg('Mort naturelle à 100 ans 🪦')}if(game.dead)show('deathScene')}function updateAge(){let y=getYears(),st='Bébé canard',sc=.75;if(y>=2){st='Enfant';sc=.9}if(y>=5){st='Ado';sc=1.05}if(y>=9){st='Adulte';sc=1.2}if(y>=70){st='Ancien';sc=1.25}$('age').textContent=y+' ans';$('stage').textContent=st;$('job').textContent=game.job+' XP '+game.jobXP;$('duck').style.transform=`scale(${sc})`}
function drawBackdrop(){const b=$('backdrop');b.innerHTML='';if(game.room==='city'){b.innerHTML=`<div class="cityMap"><div class="cityTile" onclick="goRoom('living')">🏠 Maison</div><div class="cityTile" onclick="goRoom('shop')">🏪 Magasin</div><div class="cityTile" onclick="goRoom('school')">🏫 École</div><div class="cityTile" onclick="mini('job')">💼 Travail</div><div class="cityTile" onclick="driveCar()">🚗 Voiture</div><div class="cityTile" onclick="goRoom('garden')">🌳 Jardin</div><div class="cityTile" onclick="watchTV('BFMDuck')">📺 BFMDuck</div><div class="cityTile" onclick="randomWeather()">🌦️ Météo</div></div>`;return}if(game.room==='garden')b.innerHTML='<div class="grass"></div><div class="door" style="left:20px;top:520px" onclick="goRoom(`living`)">Salon</div>';else b.innerHTML='<div class="wallGrid"></div><div class="door" style="left:20px;top:520px" onclick="goRoom(`city`)">Ville</div><div class="windowBig" style="left:70%;top:70px"></div>'}
function drawObjects(){$('objects').innerHTML='';if(!game.objects[game.room])game.objects[game.room]={};rooms[game.room].objects.forEach(([id,visual,x,y,type])=>{if(!game.objects[game.room][id])game.objects[game.room][id]={x,y};const p=game.objects[game.room][id],d=document.createElement('div');d.className='object';d.draggable=true;d.style.left=p.x+'px';d.style.top=p.y+'px';if(type==='css')d.classList.add('furn',visual);else{d.classList.add('emoji');d.textContent=visual;d.onclick=()=>objectClick(id)}d.ondragstart=e=>{e.dataTransfer.setData('type',type==='item'?'item':'object');e.dataTransfer.setData('id',id)};$('objects').appendChild(d)})}
function objectClick(id){if(id==='tv')watchTV('BFMDuck');if(id==='fridge')quickFridge();if(id==='counter')prepareFood();if(id==='pan')cookFood();if(id==='foodShelf')openShop();if(id==='cashier')msg('Passe à la caisse en achetant dans le menu magasin.');if(['water','soapObj','towelObj'].includes(id))useOnDuck(id);if(id==='lightSwitch')toggleLight();if(id==='pool'){game.wet=100;msg('Piscine : canard mouillé 💦');update()}if(id==='board'||id==='desk')studyQuiz()}
function drawPlaced(){$('placed').innerHTML='';game.placed.filter(p=>p.room===game.room).forEach(p=>{const d=document.createElement('div');d.className='placedItem';d.textContent=icon(p.item);d.draggable=true;d.style.left=p.x+'px';d.style.top=p.y+'px';d.ondragstart=e=>{e.dataTransfer.setData('type','placed');e.dataTransfer.setData('id',p.id)};$('placed').appendChild(d)})}
function drawFamily(){const f=$('familyLayer');f.innerHTML='';if(game.partner&&game.room==='living')sprite('🦆',680,455);if(game.children.length&&['living','garden'].includes(game.room))game.children.forEach((c,i)=>sprite(childIcon(c),760+i*70,460));if(game.pet&&['living','garden'].includes(game.room))sprite(game.pet==='chat'?'🐱':'🐶',930,470)}
function sprite(ic,x,y){const d=document.createElement('div');d.className='familySprite';d.textContent=ic;d.style.left=x+'px';d.style.top=y+'px';$('familyLayer').appendChild(d)}function childIcon(c){const y=getYears()-c.birthYear;return y>=13?'🧒':y>=5?'🐤':'👶'}
function drawInventory(){const keys=['salad','bread','fish','prep','meal','soap','towel','toy'];$('inventory').innerHTML='';keys.forEach(id=>{const d=document.createElement('div');d.className='slot';d.draggable=(game.inventory[id]||0)>0;d.textContent=(game.inventory[id]||0)>0?icon(id)+' '+game.inventory[id]:'—';d.ondragstart=e=>{if((game.inventory[id]||0)<=0)return;e.dataTransfer.setData('type','inventory');e.dataTransfer.setData('id',id)};$('inventory').appendChild(d)})}
function icon(id){return{salad:'🥬',bread:'🍞',fish:'🐟',meal:'🍲',soap:'🧼',towel:'🧺',prep:'🔪',toy:'🧸'}[id]||'❓'}
function goRoom(r){game.room=r;game.duckX=450;game.duckY=320;update()}function moveDuck(dir){if(isSleeping())return;const d=$('duck');let step=38;if(dir==='run'){d.classList.add('running');step=90;dir='right';setTimeout(()=>d.classList.remove('running'),600)}else{d.classList.add('walking');setTimeout(()=>d.classList.remove('walking'),450)}if(dir==='up')game.duckY-=step;if(dir==='down')game.duckY+=step;if(dir==='left')game.duckX-=step;if(dir==='right')game.duckX+=step;game.duckX=clamp(game.duckX,0,$('room').clientWidth-150);game.duckY=clamp(game.duckY,0,$('room').clientHeight-155);checkDuckPlace();update()}
function roomDrop(e){e.preventDefault();if(isSleeping())return;const type=e.dataTransfer.getData('type'),id=e.dataTransfer.getData('id'),r=$('room').getBoundingClientRect(),x=clamp(e.clientX-r.left-55,0,r.width-140),y=clamp(e.clientY-r.top-55,0,r.height-140);if(type==='duck'){game.duckX=x;game.duckY=y;checkDuckPlace()}else if(type==='inventory'){placeInventory(id,x,y)}else if(type==='placed'){movePlaced(id,x,y)}else{if(!game.objects[game.room])game.objects[game.room]={};game.objects[game.room][id]={x,y}}update()}
function gravity(){if(!game||isSleeping()||game.dead)return;const ground=$('room').clientHeight-170;let ch=false;if(game.duckY<ground&&game.room!=='city'){game.duckY=Math.min(ground,game.duckY+6);ch=true}game.placed.forEach(p=>{if(p.room===game.room&&p.y<ground+40){p.y=Math.min(ground+40,p.y+5);ch=true}});if(ch)update()}
function placeInventory(id,x,y){if(!game.inventory[id])return;game.inventory[id]--;game.placed.push({id:'p'+Date.now()+Math.random(),item:id,room:game.room,x,y});msg(icon(id)+' posé.')}function movePlaced(pid,x,y){const p=game.placed.find(i=>i.id===pid);if(p){p.x=x;p.y=y}}function consumePlaced(pid){const i=game.placed.findIndex(p=>p.id===pid);if(i>=0)game.placed.splice(i,1)}
function useOnDuck(id){let item=id;if(id.startsWith('p')){const p=game.placed.find(x=>x.id===id);if(!p)return;item=p.item;consumePlaced(id)}if(item==='meal'){game.hunger=clamp(game.hunger+45,0,100);$('duck').classList.add('eating');setTimeout(()=>$('duck').classList.remove('eating'),1600);sound('eat');game.dailyStats.meals++;trackDaily();msg('Le canard mange.')}else if(item==='water'){game.wet=100;$('duck').classList.add('showering');setTimeout(()=>$('duck').classList.remove('showering'),2000);sound('water');msg('Douche : mouillé.')}else if(item==='soap'||item==='soapObj'){game.clean=clamp(game.clean+35,0,100);msg('Savon : propreté +35.')}else if(item==='towel'||item==='towelObj'){game.wet=0;msg('Séché.')}else msg('Il faut cuisiner avant.');update()}
function quickFridge(){game.inventory.salad++;game.inventory.bread++;msg('Frigo rapide : + salade + pain.');update()}function quickFeed(){if(game.inventory.meal<=0)return msg('Pas de repas. Cuisine avant.');game.inventory.meal--;useOnDuck('meal')}function prepareFood(){if(game.room!=='kitchen')return msg('Va en cuisine.');const food=game.placed.find(p=>p.room==='kitchen'&&['salad','bread','fish'].includes(p.item));if(food){consumePlaced(food.id);game.inventory.prep++;msg('Préparation terminée 🔪');update()}else msg('Pose nourriture dans la cuisine.')}function cookFood(){if(game.room!=='kitchen')return msg('Va en cuisine.');if(game.inventory.prep<=0)return msg('Prépare avant.');game.inventory.prep--;game.inventory.meal++;msg('Repas cuit 🍳');update()}
function checkDuckPlace(){if(game.room==='bedroom'){const b=game.objects.bedroom?.bed;if(b&&distance(game.duckX,game.duckY,b.x,b.y)<210)sleepDuck()}if(game.room==='garden'){const pool=game.objects.garden?.pool;if(pool&&distance(game.duckX,game.duckY,pool.x,pool.y)<210){game.wet=100;msg('Piscine : mouillé 100%')}}}function sleepDuck(){game.sleep=100;game.sleepUntil=Date.now()+game.sleepDuration;$('duck').classList.add('sleepAnim');sound('sleep');msg('Le canard dort.');updateSleep()}
function updateCover(){const c=$('cover');if(isSleeping()&&game.room==='bedroom'){c.classList.remove('hidden');c.style.left=game.duckX+5+'px';c.style.top=game.duckY+80+'px'}else{c.classList.add('hidden');$('duck').classList.remove('sleepAnim')}}function updateWet(){const d=$('drops');if(game.wet>0){d.classList.remove('hidden');d.style.left=game.duckX+85+'px';d.style.top=game.duckY+5+'px'}else d.classList.add('hidden')}
function openShop(){modal('Magasin',`<button onclick="buyItem('salad')">🥬 Salade 20€</button><button onclick="buyItem('bread')">🍞 Pain 15€</button><button onclick="buyItem('fish')">🐟 Poisson 35€</button><button onclick="buyItem('soap')">🧼 Savon 25€</button><button onclick="buyItem('towel')">🧺 Serviette 40€</button><button onclick="buyItem('toy')">🧸 Jouet 50€</button>`)}function buyItem(id){const p={salad:20,bread:15,fish:35,soap:25,towel:40,toy:50};let price=p[id];if(game.daily&&game.daily.promo){if(game.daily.promo==='Salade -50%'&&id==='salad')price=Math.ceil(price/2);if(game.daily.promo==='Pain -50%'&&id==='bread')price=Math.ceil(price/2);if(game.daily.promo==='Poisson -50%'&&id==='fish')price=Math.ceil(price/2);if(game.daily.promo==='Savon -50%'&&id==='soap')price=Math.ceil(price/2);if(game.daily.promo==='Jouet -50%'&&id==='toy')price=Math.ceil(price/2);}if(game.money<price)return msg('Pas assez.');game.money-=price;game.inventory[id]++;sound('buy');update();msg('Acheté : '+icon(id)+' ('+price+'€)')}
function openLife(type){if(type==='date')duckDate();if(type==='family')familyMenu();if(type==='pet')petMenu();if(type==='car')carMenu();if(type==='tv')tvMenu()}
function duckDate(){if(game.partner)return modal('DuckDate',`<p>Partenaire : ${game.partner} | Amour ${game.love}</p><button onclick="dateAtGarden()">Rendez-vous jardin</button><button onclick="marry()">Mariage 500€</button><button onclick="divorce()">Divorce</button>`);const p=profiles[Math.floor(Math.random()*profiles.length)];modal('DuckDate',`<p>Profil : ${p.name}</p><p>Compatibilité requise : ${p.need}</p><button onclick="answerDate(20)">Réponse drôle</button><button onclick="answerDate(-10)">Réponse nulle</button><button onclick="likeProfile('${p.name}',${p.need})">Aimer</button>`)}function answerDate(v){game.love=clamp(game.love+v,0,100);msg('Amour '+(v>0?'+':'')+v);update()}function likeProfile(n,need){if(game.love<need)return msg('Pas assez de compatibilité.');game.partner=n;unlock('Premier couple');msg('Tu es avec '+n);update()}function dateAtGarden(){goRoom('garden');game.love=clamp(game.love+15,0,100);update()}function marry(){if(!game.partner)return;if(game.money<500)return msg('500€ requis.');game.money-=500;game.married=true;unlock('Premier mariage');update()}function divorce(){game.partner=null;game.married=false;game.love=0;update()}
function familyMenu(){modal('Famille',`<p>Enfants : ${game.children.length}</p><button onclick="haveChild()">Avoir un enfant 300€</button>`)}function haveChild(){if(!game.partner)return msg('Partenaire requis.');if(game.money<300)return msg('300€ requis.');game.money-=300;game.children.push({birthYear:getYears(),name:'Bébou '+(game.children.length+1)});unlock('Premier enfant');update()}
function petMenu(){modal('Animal',`<p>Animal : ${game.pet||'aucun'}</p><button onclick="adoptPet('chien')">Adopter chien 250€</button><button onclick="adoptPet('chat')">Adopter chat 250€</button>`)}function adoptPet(p){if(game.pet)return msg('Tu as déjà un animal.');if(game.money<250)return msg('250€ requis.');game.money-=250;game.pet=p;unlock('Premier animal');update()}
function carMenu(){modal('Voiture',`<p>Voiture : ${game.car?'oui':'non'} | Essence ${game.fuel}</p><button onclick="buyCar()">Acheter 700€</button><button onclick="driveCar()">Conduire</button>`)}function buyCar(){if(game.car)return msg('Déjà achetée.');if(game.money<700)return msg('700€ requis.');game.money-=700;game.car=true;unlock('Première voiture');update()}function driveCar(){if(!game.car)return msg('Achète une voiture.');show('driveOverlay');let pos=45,speed=0;const car=$('carPlayer');document.onkeydown=e=>{if($('driveOverlay').classList.contains('hidden'))return;if(e.key==='ArrowLeft')pos-=5;if(e.key==='ArrowRight')pos+=5;if(e.key==='ArrowUp')speed+=8;if(e.key==='ArrowDown')speed-=8;pos=clamp(pos,5,85);speed=clamp(speed,0,100);car.style.left=pos+'%';car.style.bottom=(20+speed*2.6)+'px';game.fuel=clamp(game.fuel-1,0,100);if(speed>90){hide('driveOverlay');document.onkeydown=null;goRoom('city');game.happy=clamp(game.happy+15,0,100);msg('Trajet fini 🚗');update()}}}
function tvMenu(){modal('Télévision',`<button onclick="watchTV('BFMDuck')">BFMDuck</button><button onclick="watchTV('Météo')">Météo</button><button onclick="watchTV('Dessins animés')">Dessins animés</button><button onclick="postDuckTube()">Poster DuckTube</button>`)}function watchTV(ch='BFMDuck'){game.happy=clamp(game.happy+6,0,100);game.dailyStats.tv++;trackDaily();sound('tv');msg('TV : '+ch);update()}function postDuckTube(){const gain=Math.floor(Math.random()*120)+20;game.followers+=gain;game.money+=Math.floor(gain/3);unlock('DuckTubeur');msg('DuckTube : +'+gain+' vues, +'+Math.floor(gain/3)+'€');update()}
function mini(t){show('miniOverlay');$('miniArea').innerHTML='';clearInterval(miniInterval);if(t==='food')miniFood();else tapMini(t,8,()=>miniReward(t))}function closeMini(){hide('miniOverlay');$('miniArea').innerHTML='';clearInterval(miniInterval)}function miniFood(){$('miniTitle').textContent='Nourriture';let score=0;const a=$('miniArea'),b=document.createElement('div');b.className='basket';b.style.left='180px';a.appendChild(b);a.onmousemove=e=>{const r=a.getBoundingClientRect();b.style.left=clamp(e.clientX-r.left-45,0,r.width-95)+'px'};function spawn(){const f=document.createElement('div');f.className='fallingFood';f.textContent='🥬';f.style.left=Math.random()*(a.clientWidth-40)+'px';f.style.top='-40px';a.appendChild(f);let y=-40;const fall=setInterval(()=>{y+=6;f.style.top=y+'px';const fx=parseInt(f.style.left),bx=parseInt(b.style.left);if(y>a.clientHeight-80&&fx>bx-30&&fx<bx+95){clearInterval(fall);f.remove();score++;if(score>=5){game.inventory.salad+=2;update();closeMini()}}if(y>a.clientHeight){clearInterval(fall);f.remove()}},30)}miniInterval=setInterval(spawn,650)}function tapMini(title,needed,reward){$('miniTitle').textContent=title;$('miniInfo').textContent='Clique les étoiles';let score=0;const a=$('miniArea');function spawn(){const t=document.createElement('div');t.className='tapTarget';t.textContent='⭐';t.style.left=Math.random()*(a.clientWidth-80)+'px';t.style.top=Math.random()*(a.clientHeight-80)+'px';t.onclick=()=>{score++;t.remove();$('miniInfo').textContent='Score : '+score+'/'+needed;if(score>=needed){reward();update();closeMini()}else spawn()};a.appendChild(t)}spawn()}function miniReward(t){if(t==='clean')game.clean=100;if(t==='job'){game.money+=120;game.job='Employé';game.jobXP++;unlock('Premier travail')}if(t==='school')studyQuiz(true);if(t==='garden')game.happy=clamp(game.happy+20,0,100);if(t==='console')game.happy=clamp(game.happy+15,0,100);msg('Mini-jeu réussi : '+t)}
function studyQuiz(fromMini=false){const qs=[['2+2','4'],['5+5','10'],['10-3','7']];const q=qs[Math.floor(Math.random()*qs.length)];const ans=fromMini?q[1]:prompt('École : '+q[0]+' = ?');if(ans===q[1]){game.school++;game.jobXP++;game.dailyStats.school++;trackDaily();$('duck').classList.add('schoolAnim');setTimeout(()=>$('duck').classList.remove('schoolAnim'),2500);msg('Bonne réponse : XP +1')}else msg('Raté. Le canard fait semblant de comprendre.');update()}function quickFridge(){game.inventory.salad++;game.inventory.bread++;msg('Frigo rapide : + salade + pain.');update()}function quickFeed(){if(game.inventory.meal<=0)return msg('Pas de repas. Cuisine avant.');game.inventory.meal--;useOnDuck('meal')}
function randomWeather(){const w=['Soleil','Pluie 🌧️','Neige ❄️'];game.weather=w[Math.floor(Math.random()*w.length)];if(game.weather.includes('Pluie'))game.wet=80;update()}function birthday(){game.happy=100;game.money+=20;addJournal('Anniversaire : j’ai reçu 20€. Pas énorme mais ok.');msg('Anniversaire 🎂');update()}function addJournal(t){if(!game)return;game.journal.unshift('Année '+getYears()+' : '+t);game.journal=game.journal.slice(0,20)}function showJournal(){modal('Journal du canard',game.journal.length?game.journal.map(x=>'<p>'+x+'</p>').join(''):'<p>Rien encore.</p>')}function unlock(a){if(!game.achievements.includes(a)){game.achievements.push(a);msg('Succès : '+a+' 🏆')}}function showAchievements(){modal('Succès',game.achievements.length?game.achievements.map(x=>'<p>🏆 '+x+'</p>').join(''):'<p>Aucun succès.</p>')}

function checkDaily(){
  if(!game.daily) game.daily={lastDay:0,giftClaimed:false,mission:'',promo:'',event:'',progress:0,done:false};
  const today=Math.floor(Date.now()/86400000);
  if(game.daily.lastDay!==today){
    game.daily.lastDay=today;
    game.daily.giftClaimed=false;
    game.daily.progress=0;
    game.daily.done=false;
    game.dailyStats={meals:0,school:0,earned:0,garden:0,bath:0,tv:0};
    const missions=['Manger 3 repas','Aller à l’école','Gagner 200€','Faire une activité jardin','Regarder la TV'];
    const promos=['Salade -50%','Pain -50%','Poisson -50%','Savon -50%','Jouet -50%'];
    const events=['Soleil bonus','Pluie surprise','Promo magasin','Loto léger','Journée calme'];
    game.daily.mission=missions[Math.floor(Math.random()*missions.length)];
    game.daily.promo=promos[Math.floor(Math.random()*promos.length)];
    game.daily.event=events[Math.floor(Math.random()*events.length)];
    addJournal('Nouveau jour : '+game.daily.mission+' / '+game.daily.promo+' / '+game.daily.event);
  }
}
function drawDailyPanel(){
  const p=$('dailyPanel');
  if(!p||!game.daily)return;
  p.innerHTML=`<span class="dailyPill">🎯 ${game.daily.mission||'Mission'}</span><span class="dailyPill">🏪 ${game.daily.promo||'Promo'}</span><span class="dailyPill">🌦️ ${game.daily.event||'Événement'}</span><span class="dailyPill">🎁 ${game.daily.giftClaimed?'Cadeau pris':'Cadeau dispo'}</span>`;
}
function showDaily(){
  checkDaily();
  modal('Quotidien V20',`<p><b>Mission :</b> ${game.daily.mission}</p><p><b>Promo :</b> ${game.daily.promo}</p><p><b>Événement :</b> ${game.daily.event}</p><p><b>Progression :</b> ${dailyProgressText()}</p><button onclick="claimDailyGift()">🎁 Cadeau du jour</button>`);
}
function dailyProgressText(){
  const m=game.daily.mission;
  if(m==='Manger 3 repas')return game.dailyStats.meals+'/3 repas';
  if(m==='Aller à l’école')return game.dailyStats.school+'/1 cours';
  if(m==='Gagner 200€')return game.dailyStats.earned+'/200€';
  if(m==='Faire une activité jardin')return game.dailyStats.garden+'/1 activité';
  if(m==='Regarder la TV')return game.dailyStats.tv+'/1 TV';
  return '0';
}
function trackDaily(){
  if(!game.daily||game.daily.done)return;
  const m=game.daily.mission;
  let ok=false;
  if(m==='Manger 3 repas'&&game.dailyStats.meals>=3)ok=true;
  if(m==='Aller à l’école'&&game.dailyStats.school>=1)ok=true;
  if(m==='Gagner 200€'&&game.dailyStats.earned>=200)ok=true;
  if(m==='Faire une activité jardin'&&game.dailyStats.garden>=1)ok=true;
  if(m==='Regarder la TV'&&game.dailyStats.tv>=1)ok=true;
  if(ok){
    game.daily.done=true;
    game.money+=150;
    unlock('Mission quotidienne');
    addJournal('Mission quotidienne réussie : '+m+' (+150€)');
    msg('Mission quotidienne réussie : +150€ 🎯');
  }
}
function claimDailyGift(){
  checkDaily();
  if(game.daily.giftClaimed)return msg('Cadeau déjà récupéré aujourd’hui.');
  game.daily.giftClaimed=true;
  game.money+=100;
  if(Math.random()<0.01){
    const rares=['🐤 Canard doré','👑 Couronne','🚗 Voiture légendaire','📺 TV géante','🏆 Trophée du maire'];
    const r=rares[Math.floor(Math.random()*rares.length)];
    if(!game.collection.includes(r))game.collection.push(r);
    msg('Cadeau quotidien : +100€ et objet rare '+r+' !');
    unlock('Objet rare');
  }else{
    msg('Cadeau quotidien : +100€ 🎁');
  }
  addJournal('J’ai récupéré mon cadeau quotidien.');
  update();
}
function showCollection(){
  const items=game.collection.length?game.collection.map(x=>`<div class="collectionItem">${x}</div>`).join(''):'<p>Aucun objet rare. Chance 1% avec le cadeau quotidien.</p>';
  modal('Collection rare',`<div class="collectionGrid">${items}</div>`);
}
function drawRoomActions(){
  const p=$('roomActions');
  if(!p)return;
  let h='';
  if(game.room==='bath')h=`<h3>Salle de bain V20</h3><button onclick="brushTeeth()">🪥 Brosser dents</button><button onclick="bubbleBath()">🛁 Bain moussant</button><button onclick="useOnDuck('water')">🚿 Douche</button><button onclick="useOnDuck('towel')">🧺 Sécher</button>`;
  else if(game.room==='kitchen')h=`<h3>Cuisine V20</h3><button onclick="quickFridge()">🧊 Frigo</button><button onclick="showRecipes()">📖 Recettes</button><button onclick="prepareFood()">🔪 Préparer</button><button onclick="cookFood()">🍳 Cuire</button>`;
  else if(game.room==='living')h=`<h3>Salon V20</h3><button onclick="watchTV('BFMDuck')">📺 BFMDuck</button><button onclick="watchTV('Dessins animés')">📺 Dessins animés</button><button onclick="mini('console')">🎮 Console</button>`;
  else if(game.room==='garden')h=`<h3>Jardin V20</h3><button onclick="gardenActivity('foot')">⚽ Football</button><button onclick="gardenActivity('jardinage')">🌻 Jardinage</button><button onclick="gardenActivity('peche')">🎣 Pêche</button><button onclick="poolSwim()">🏊 Piscine</button>`;
  else if(game.room==='bedroom')h=`<h3>Chambre V20</h3><button onclick="sleepDuck()">😴 Dormir</button><button onclick="readBook()">📖 Lire</button><button onclick="nap()">🛏️ Sieste</button>`;
  else if(game.room==='shop')h=`<h3>Magasin V20</h3><button onclick="openShop()">🛒 Acheter</button><button onclick="showDaily()">🏪 Promo du jour</button>`;
  else if(game.room==='school')h=`<h3>École V20</h3><button onclick="studyQuiz()">➕ Maths</button><button onclick="schoolSubject('français')">📖 Français</button><button onclick="schoolSubject('sciences')">🧪 Sciences</button>`;
  else h=`<h3>Ville V20</h3><button onclick="showDaily()">📅 Quotidien</button><button onclick="claimDailyGift()">🎁 Cadeau</button>`;
  p.innerHTML=h;
}
function brushTeeth(){game.happy=clamp(game.happy+5,0,100);game.clean=clamp(game.clean+5,0,100);game.dailyStats.bath++;addJournal('J’ai brossé mes dents. Très civilisé.');msg('Dents propres : bonheur +5 🪥');update();}
function bubbleBath(){game.happy=clamp(game.happy+10,0,100);game.clean=100;game.wet=80;game.dailyStats.bath++;msg('Bain moussant : propreté 100, bonheur +10 🛁');update();}
function showRecipes(){modal('Recettes V20',`<div class="recipeCard"><b>Sandwich</b><br>pain + salade</div><div class="recipeCard"><b>Poisson grillé</b><br>poisson préparé + poêle</div><div class="recipeCard"><b>Salade complète</b><br>salade + poisson</div><button onclick="cookFavorite()">Préparer plat préféré</button>`);}
function cookFavorite(){if(game.inventory.salad<=0)return msg('Il faut au moins une salade.');game.inventory.salad--;game.inventory.meal++;game.happy=clamp(game.happy+10,0,100);msg('Plat préféré préparé : repas + bonheur 🍽️');update();}
function gardenActivity(type){game.happy=clamp(game.happy+10,0,100);game.dailyStats.garden++;trackDaily();addJournal('Activité jardin : '+type);msg('Activité jardin : bonheur +10 🌳');update();}
function poolSwim(){game.wet=100;game.happy=clamp(game.happy+8,0,100);game.dailyStats.garden++;trackDaily();msg('Piscine : mouillé 100%, bonheur +8 🏊');update();}
function readBook(){game.happy=clamp(game.happy+6,0,100);game.school++;msg('Lecture : bonheur +6, école +1 📖');update();}
function nap(){game.sleep=clamp(game.sleep+25,0,100);msg('Sieste : sommeil +25 🛏️');update();}
function schoolSubject(s){game.school++;game.jobXP++;game.dailyStats.school++;trackDaily();msg('Cours de '+s+' : XP +1');update();}

function openSettings(){modal('Réglages',`<label>Volume <input id="setVolume" type="range" min="0" max="0.2" step="0.01" value="${game.settings.volume}"></label><label><input id="setMusic" type="checkbox" ${game.settings.music?'checked':''}> Musique ON/OFF</label><label><input id="setDark" type="checkbox" ${game.settings.dark?'checked':''}> Mode sombre</label><label>Vitesse du temps <select id="setSpeed"><option value="0.5">Lent</option><option value="1">Normal</option><option value="2">Rapide</option><option value="4">Très rapide</option></select></label><label><input id="setOneYear" type="checkbox" ${game.settings.oneDayOneYear?'checked':''}> 1 jour = 1 an</label><label><input id="setAuto" type="checkbox" ${game.settings.autosave?'checked':''}> Auto-save</label><button onclick="applySettingsFromModal()">Appliquer</button>`);setTimeout(()=>{$('setSpeed').value=game.settings.timeSpeed},0)}function applySettingsFromModal(){game.settings.volume=+$('setVolume').value;game.settings.music=$('setMusic').checked;game.settings.dark=$('setDark').checked;game.settings.timeSpeed=+$('setSpeed').value;game.settings.oneDayOneYear=$('setOneYear').checked;game.settings.autosave=$('setAuto').checked;applySettings();update()}function applySettings(){document.body.classList.toggle('dark',game.settings.dark);if(game.settings.music)startMusic();else stopMusic()}function startMusic(){if(musicOsc)return;try{musicCtx=new AudioContext();musicOsc=musicCtx.createOscillator();const g=musicCtx.createGain();musicOsc.frequency.value=180;g.gain.value=game.settings.volume/2;musicOsc.connect(g);g.connect(musicCtx.destination);musicOsc.start()}catch(e){}}function stopMusic(){try{musicOsc&&musicOsc.stop();musicCtx&&musicCtx.close()}catch(e){}musicOsc=null;musicCtx=null}
function modal(t,html){$('modalTitle').textContent=t;$('modalContent').innerHTML=html;show('modalOverlay')}function toggleLight(){document.body.classList.toggle('dark');msg('Lumière changée.')}function openDev(){show('devOverlay');$('devLocked').classList.toggle('hidden',devUnlocked);$('devPanel').classList.toggle('hidden',!devUnlocked);fillDev()}function unlockDev(){if($('devCode').value==='2004'){devUnlocked=true;$('devLocked').classList.add('hidden');$('devPanel').classList.remove('hidden');fillDev()}else alert('Code faux')}function fillDev(){if(!game)game=defaultGame();$('devMoney').value=game.money;$('devAge').value=getYears();$('devHunger').value=game.hunger;$('devClean').value=game.clean;$('devSleep').value=game.sleep;$('devHappy').value=game.happy;$('devWet').value=game.wet}function applyDev(){game.money=+devMoney.value;game.birth=Date.now()-+devAge.value*86400000;game.hunger=clamp(+devHunger.value,0,100);game.clean=clamp(+devClean.value,0,100);game.sleep=clamp(+devSleep.value,0,100);game.happy=clamp(+devHappy.value,0,100);game.wet=clamp(+devWet.value,0,100);game.dead=false;hide('deathScene');update()}
function passTime(){if(!game||isSleeping()||game.dead)return;checkDaily();game.hour=(game.hour+Math.max(1,Math.round(game.settings.timeSpeed)))%24;game.hunger=clamp(game.hunger-2*game.settings.timeSpeed,0,100);game.clean=clamp(game.clean-1*game.settings.timeSpeed,0,100);game.sleep=clamp(game.sleep-2*game.settings.timeSpeed,0,100);game.happy=clamp(game.happy-1*game.settings.timeSpeed,0,100);game.wet=clamp(game.wet-4*game.settings.timeSpeed,0,100);if(Math.random()<.2)addJournal('J’ai survécu une journée de plus. Coin.');game.lastVisit=Date.now();update()}function updateSleep(){if(!game)return;if(isSleeping()){show('sleepOverlay');const l=game.sleepUntil-Date.now();$('timer').textContent=Math.floor(l/60000)+' min '+Math.floor((l%60000)/1000)+' sec'}else hide('sleepOverlay');updateCover()}function isSleeping(){return game&&Date.now()<game.sleepUntil}function sound(type){try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=type==='water'?420:type==='tv'?260:type==='sleep'?180:type==='buy'?620:type==='cook'?520:300;o.connect(g);g.connect(a.destination);g.gain.value=game.settings.volume;o.start();setTimeout(()=>{o.stop();a.close()},160)}catch(e){}}
function resetGame(){if(confirm('Recommencer ?')){localStorage.removeItem(STORAGE_PREFIX+currentSlot);location.reload()}}function msg(t){$('msg').textContent=t}function clamp(v,min,max){return Math.min(max,Math.max(min,v))}function distance(x1,y1,x2,y2){return Math.sqrt((x1-x2)**2+(y1-y2)**2)}
